name: Create Release
on:
  workflow_dispatch:
      inputs:
        Branch:
          description: 'Select Target Branch (default: main)'
          required: true
          default: 'main'
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --watch=false --browsers=ChromeHeadless
    - run: npm install -D @semantic-release/exec @semantic-release/changelog @semantic-release/git @semantic-release/github
    - run: npx semantic-release -b ${{ inputs.Branch }} --dry-run
