name: Create Release
on:
  workflow_dispatch:
      inputs:
        Branch:
          description: 'Select Target Branch (default: main)'
          required: true
          default: 'main'
jobs:
  prepare:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        uses: codfish/semantic-release-action@v1
        with:
          branches: ${{ inputs.Branch }}
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              '@semantic-release/release-notes-generator',
              '@semantic-release/github',
              '@semantic-release/git',
              '@semantic-release/changelog',
              '@semantic-release/exec',
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
