name: Create Release
on:
  workflow_dispatch:
      inputs:
        Branch:
          description: 'Select Target Branch (default: main)'
          required: true
          default: 'main'
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    container: node:slim
    steps:
      - run: apt-get update && apt-get install -y git
      - run: npm install @semantic-release/exec -D
      - run: npm install @semantic-release/changelog -D
      - run: npm install @semantic-release/git -D
      - run: npm install @semantic-release/github -D
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npx semantic-release -b ${{ inputs.Branch }} --dry-run
