name: Create Release
on:
  workflow_dispatch:
      inputs:
        Branch:
          description: 'Select Target Branch (default: main)'
          required: true
          default: 'main'
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: node:slim
    - run: apt-update && apt-install -y git
    - run: npm install -D @semantic-release/exec @semantic-release/changelog @semantic-release/git @semantic-release/github
    - run: npx semantic-release -b ${{ inputs.Branch }} --dry-run
