name: Create Release
on:
  workflow_dispatch:
      inputs:
        Branch:
          description: 'Select Target Branch (default: main)'
          required: true
          default: 'main'
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    container:
      image: node:slim
      options: --user root
    steps:
      - run: apt-get update && apt-get install -y git
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0
      - name: install deps
        run: |
          npm install @semantic-release/exec -D
          npm install @semantic-release/changelog -D
          npm install @semantic-release/git -D
          npm install @semantic-release/github -D
      - name: Create new Release
        run: |
          pwd
          ls -la
          npx semantic-release -b ${{ inputs.Branch }} --dry-run
